config/routes.rb
Rails.application.routes.draw do
  resources :duties
  resources :pupils
  resources :class_rooms
  resources :schools
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  get 'dashboard', to: 'static#dashboard'
  root 'static#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/duty.rb
# == Schema Information
#
# Table name: duties
#
#  id              :integer          not null, primary key
#  class_room_id   :integer
#  start_date      :date
#  end_date        :date
#  parents_in_duty :integer
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Duty < ApplicationRecord
  belongs_to :user
  belongs_to :class_room
end

app/controllers/duties_controller.rb
class DutiesController < ApplicationController
  before_action :set_duty, only: [:show, :edit, :update, :destroy]

  # GET /duties
  # GET /duties.json
  def index
    @duties = Duty.all
  end

  # GET /duties/1
  # GET /duties/1.json
  def show
  end

  # GET /duties/new
  def new
    @duty = Duty.new
  end

  # GET /duties/1/edit
  def edit
  end

  # POST /duties
  # POST /duties.json
  def create
    @duty = Duty.new(duty_params)

    respond_to do |format|
      if @duty.save
        format.html { redirect_to @duty, notice: 'Duty was successfully created.' }
        format.json { render :show, status: :created, location: @duty }
      else
        format.html { render :new }
        format.json { render json: @duty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duties/1
  # PATCH/PUT /duties/1.json
  def update
    respond_to do |format|
      if @duty.update(duty_params)
        format.html { redirect_to @duty, notice: 'Duty was successfully updated.' }
        format.json { render :show, status: :ok, location: @duty }
      else
        format.html { render :edit }
        format.json { render json: @duty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duties/1
  # DELETE /duties/1.json
  def destroy
    @duty.destroy
    respond_to do |format|
      format.html { redirect_to duties_url, notice: 'Duty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duty
      @duty = Duty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duty_params
      params.require(:duty).permit(:class_room_id, :start_date, :end_date, :parents_in_duty, :user_id)
    end
end

app/helpers/duties_helper.rb
module DutiesHelper
end

app/views/duties/_form.html.erb
<%= form_for(duty) do |f| %>
  <% if duty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duty.errors.count, "error") %> prohibited this duty from being saved:</h2>

      <ul>
      <% duty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_room_id %>
    <%= f.number_field :class_room_id %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="field">
    <%= f.label :parents_in_duty %>
    <%= f.number_field :parents_in_duty %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/duties/edit.html.erb
<h1>Editing Duty</h1>

<%= render 'form', duty: @duty %>

<%= link_to 'Show', @duty %> |
<%= link_to 'Back', duties_path %>

app/views/duties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Duties</h1>

<table>
  <thead>
    <tr>
      <th>Class room</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Parents in duty</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @duties.each do |duty| %>
      <tr>
        <td><%= duty.class_room_id %></td>
        <td><%= duty.start_date %></td>
        <td><%= duty.end_date %></td>
        <td><%= duty.parents_in_duty %></td>
        <td><%= duty.user_id %></td>
        <td><%= link_to 'Show', duty %></td>
        <td><%= link_to 'Edit', edit_duty_path(duty) %></td>
        <td><%= link_to 'Destroy', duty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duty', new_duty_path %>

app/views/duties/new.html.erb
<h1>New Duty</h1>

<%= render 'form', duty: @duty %>

<%= link_to 'Back', duties_path %>

app/views/duties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class room:</strong>
  <%= @duty.class_room_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @duty.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @duty.end_date %>
</p>

<p>
  <strong>Parents in duty:</strong>
  <%= @duty.parents_in_duty %>
</p>

<p>
  <strong>User:</strong>
  <%= @duty.user_id %>
</p>

<%= link_to 'Edit', edit_duty_path(@duty) %> |
<%= link_to 'Back', duties_path %>