config/routes.rb
Rails.application.routes.draw do
  resources :duties
  resources :pupils
  resources :class_rooms
  resources :schools
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  get 'dashboard', to: 'static#dashboard'
  root 'static#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/class_room.rb
# == Schema Information
#
# Table name: class_rooms
#
#  id         :integer          not null, primary key
#  school_id  :integer
#  name       :string
#  number     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ClassRoom < ApplicationRecord
  has_many :pupils
  has_many :duties
  belongs_to :school
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
  before_action :set_class_room, only: [:show, :edit, :update, :destroy]

  # GET /class_rooms
  # GET /class_rooms.json
  def index
    @class_rooms = ClassRoom.all
  end

  # GET /class_rooms/1
  # GET /class_rooms/1.json
  def show
  end

  # GET /class_rooms/new
  def new
    @class_room = ClassRoom.new
  end

  # GET /class_rooms/1/edit
  def edit
  end

  # POST /class_rooms
  # POST /class_rooms.json
  def create
    @class_room = ClassRoom.new(class_room_params)

    respond_to do |format|
      if @class_room.save
        format.html { redirect_to @class_room, notice: 'Class room was successfully created.' }
        format.json { render :show, status: :created, location: @class_room }
      else
        format.html { render :new }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_rooms/1
  # PATCH/PUT /class_rooms/1.json
  def update
    respond_to do |format|
      if @class_room.update(class_room_params)
        format.html { redirect_to @class_room, notice: 'Class room was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_room }
      else
        format.html { render :edit }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_rooms/1
  # DELETE /class_rooms/1.json
  def destroy
    @class_room.destroy
    respond_to do |format|
      format.html { redirect_to class_rooms_url, notice: 'Class room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_room
      @class_room = ClassRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_room_params
      params.require(:class_room).permit(:school_id, :name, :number)
    end
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/views/class_rooms/_form.html.erb
<%= form_for(class_room) do |f| %>
  <% if class_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(class_room.errors.count, "error") %> prohibited this class_room from being saved:</h2>

      <ul>
      <% class_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :school_id %>
    <%= f.text_field :school_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_rooms/edit.html.erb
<h1>Editing Class Room</h1>

<%= render 'form', class_room: @class_room %>

<%= link_to 'Show', @class_room %> |
<%= link_to 'Back', class_rooms_path %>

app/views/class_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Class Rooms</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_rooms.each do |class_room| %>
      <tr>
        <td><%= class_room.school_id %></td>
        <td><%= class_room.name %></td>
        <td><%= class_room.number %></td>
        <td><%= link_to 'Show', class_room %></td>
        <td><%= link_to 'Edit', edit_class_room_path(class_room) %></td>
        <td><%= link_to 'Destroy', class_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class Room', new_class_room_path %>

app/views/class_rooms/new.html.erb
<h1>New Class Room</h1>

<%= render 'form', class_room: @class_room %>

<%= link_to 'Back', class_rooms_path %>

app/views/class_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @class_room.school_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @class_room.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @class_room.number %>
</p>

<%= link_to 'Edit', edit_class_room_path(@class_room) %> |
<%= link_to 'Back', class_rooms_path %>