config/routes.rb
Rails.application.routes.draw do
  resources :duties
  resources :pupils
  resources :class_rooms
  resources :schools
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  get 'dashboard', to: 'static#dashboard'
  root 'static#home'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pupil.rb
# == Schema Information
#
# Table name: pupils
#
#  id                  :integer          not null, primary key
#  full_name           :string
#  father_name         :string
#  father_phone_number :string
#  mother_name         :string
#  mother_phone_number :string
#  class_room_id       :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Pupil < ApplicationRecord
  belongs_to :class_room
end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
  before_action :set_pupil, only: [:show, :edit, :update, :destroy]

  # GET /pupils
  # GET /pupils.json
  def index
    @pupils = Pupil.all
  end

  # GET /pupils/1
  # GET /pupils/1.json
  def show
  end

  # GET /pupils/new
  def new
    @pupil = Pupil.new
  end

  # GET /pupils/1/edit
  def edit
  end

  # POST /pupils
  # POST /pupils.json
  def create
    @pupil = Pupil.new(pupil_params)

    respond_to do |format|
      if @pupil.save
        format.html { redirect_to @pupil, notice: 'Pupil was successfully created.' }
        format.json { render :show, status: :created, location: @pupil }
      else
        format.html { render :new }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pupils/1
  # PATCH/PUT /pupils/1.json
  def update
    respond_to do |format|
      if @pupil.update(pupil_params)
        format.html { redirect_to @pupil, notice: 'Pupil was successfully updated.' }
        format.json { render :show, status: :ok, location: @pupil }
      else
        format.html { render :edit }
        format.json { render json: @pupil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pupils/1
  # DELETE /pupils/1.json
  def destroy
    @pupil.destroy
    respond_to do |format|
      format.html { redirect_to pupils_url, notice: 'Pupil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pupil
      @pupil = Pupil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pupil_params
      params.require(:pupil).permit(:full_name, :father_name, :father_phone_number, :mother_name, :mother_phone_number, :class_room_id)
    end
end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/pupils/_form.html.erb
<%= form_for(pupil) do |f| %>
  <% if pupil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pupil.errors.count, "error") %> prohibited this pupil from being saved:</h2>

      <ul>
      <% pupil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :father_name %>
    <%= f.text_field :father_name %>
  </div>

  <div class="field">
    <%= f.label :father_phone_number %>
    <%= f.text_field :father_phone_number %>
  </div>

  <div class="field">
    <%= f.label :mother_name %>
    <%= f.text_field :mother_name %>
  </div>

  <div class="field">
    <%= f.label :mother_phone_number %>
    <%= f.text_field :mother_phone_number %>
  </div>

  <div class="field">
    <%= f.label :class_room_id %>
    <%= f.number_field :class_room_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pupils/edit.html.erb
<h1>Editing Pupil</h1>

<%= render 'form', pupil: @pupil %>

<%= link_to 'Show', @pupil %> |
<%= link_to 'Back', pupils_path %>

app/views/pupils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pupils</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Father name</th>
      <th>Father phone number</th>
      <th>Mother name</th>
      <th>Mother phone number</th>
      <th>Class room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pupils.each do |pupil| %>
      <tr>
        <td><%= pupil.full_name %></td>
        <td><%= pupil.father_name %></td>
        <td><%= pupil.father_phone_number %></td>
        <td><%= pupil.mother_name %></td>
        <td><%= pupil.mother_phone_number %></td>
        <td><%= pupil.class_room_id %></td>
        <td><%= link_to 'Show', pupil %></td>
        <td><%= link_to 'Edit', edit_pupil_path(pupil) %></td>
        <td><%= link_to 'Destroy', pupil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pupil', new_pupil_path %>

app/views/pupils/new.html.erb
<h1>New Pupil</h1>

<%= render 'form', pupil: @pupil %>

<%= link_to 'Back', pupils_path %>

app/views/pupils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @pupil.full_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @pupil.father_name %>
</p>

<p>
  <strong>Father phone number:</strong>
  <%= @pupil.father_phone_number %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @pupil.mother_name %>
</p>

<p>
  <strong>Mother phone number:</strong>
  <%= @pupil.mother_phone_number %>
</p>

<p>
  <strong>Class room:</strong>
  <%= @pupil.class_room_id %>
</p>

<%= link_to 'Edit', edit_pupil_path(@pupil) %> |
<%= link_to 'Back', pupils_path %>